cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(ARRAY_TYPE "double" CACHE STRING "Тип элементов массива: float или double")
add_executable(sine_sum main.cpp)
if(ARRAY_TYPE STREQUAL "float")
    target_compile_definitions(sine_sum PRIVATE USE_FLOAT)
endif()